---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - node_js: "4"
      env: EMBER_TRY_SCENARIO=ember-default
    - node_js: "8"
      env: EMBER_TRY_SCENARIO=ember-default


before_install:
  - npm config set spin false
  - npm update -g npm
  - npm --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
  - if [[ "$EMBER_TRY_SCENARIO" == "ember-default" ]]; then mkdir node_modules/@fizmo; node_modules/.bin/mocha node-tests --recursive; fi

